<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse Library_w-full pl-10 pr-4 py-3_c2404c_2</name>
   <tag></tag>
   <elementGuidId>5e2cb324-6099-42bd-8b96-a7492bc8d952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='lo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search books or authors...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bc003d4-37ec-49b7-9f3d-dc8594d9cf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx:101:8</value>
      <webElementGuid>e84a9c33-1826-4d5f-aad0-b0d8f5fb80ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37df6af7-6052-4119-b7e8-00abef7a2a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx</value>
      <webElementGuid>14eb717f-e826-44c0-9138-48c2eb0c42d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>d723e654-9c3a-454b-82f6-cf91240decc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BrowseLibrary.tsx</value>
      <webElementGuid>329444f2-d6c3-4858-9038-d1a1723f8745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af2a4eab-f7da-4e37-b144-f9b68cdbf1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22placeholder%22%3A%22Search%20books%20or%20authors...%22%2C%22className%22%3A%22w-full%20pl-10%20pr-4%20py-3%20bg-gray-100%20rounded-xl%20border-none%20focus%3Aoutline-none%20focus%3Aring-2%20focus%3Aring-blue-500%22%7D</value>
      <webElementGuid>8ae3a083-a3f8-46f9-89e8-f440e1b9c9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30173b13-aa79-482c-82ca-99fcce4fae5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search books or authors...</value>
      <webElementGuid>1d386ed7-a219-4781-9577-d29f02d659e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>16172d52-3511-4775-9477-81955b3cb00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>lo</value>
      <webElementGuid>8a4f0692-38dd-401b-9852-63a1f506d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500&quot;]</value>
      <webElementGuid>af8e0a60-11bf-4882-8178-0718c3394913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='lo']</value>
      <webElementGuid>de62d3d9-4e5f-4b86-a167-7e100ca5047a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/input</value>
      <webElementGuid>0edd2640-fb7d-4b6c-b1f7-9066c26c5188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6f487a9f-b0c1-4eca-ae5c-c313a985180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search books or authors...']</value>
      <webElementGuid>aa7124cf-d77c-4bc7-9c09-11bb06424c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
