<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Page120of320_bg-blue-500 text-white _ccdf62</name>
   <tag></tag>
   <elementGuidId>153fa183-7dee-4792-9d94-67e0197a8a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[2]/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a88ca02f-6be1-44cf-ad9e-34ffd7973cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\ProgressCard.tsx:46:8</value>
      <webElementGuid>a80d98b2-d493-49b6-9ccf-ecb945a77a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fe2b9f0-c658-4fe6-b80c-5a451b63813c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\ProgressCard.tsx</value>
      <webElementGuid>19c1a6ef-7a85-4b45-a545-25d1a01b7965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>fe157f4a-2e4a-498b-9d2e-8c67e6e756a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>ProgressCard.tsx</value>
      <webElementGuid>f9e373b3-4cf7-466d-94e6-75a5047c3cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc5e848c-048a-4760-809d-b7d836216d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22className%22%3A%22bg-blue-500%20text-white%20p-3%20rounded-full%20hover%3Abg-blue-600%20transition-colors%22%7D</value>
      <webElementGuid>ae0c1ad9-ffb3-4985-9a06-9272e322da8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-blue-500 text-white p-3 rounded-full hover:bg-blue-600 transition-colors</value>
      <webElementGuid>161d3388-35aa-431a-afd2-12ede905b428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-6&quot;]/div[2]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;bg-white rounded-xl shadow-sm border border-gray-100 p-4 hover:shadow-md transition-all duration-200&quot;]/div[@class=&quot;flex items-center space-x-4&quot;]/button[@class=&quot;bg-blue-500 text-white p-3 rounded-full hover:bg-blue-600 transition-colors&quot;]</value>
      <webElementGuid>844faafb-9aa1-4ee9-aedc-d416305f93fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div/div/div/button</value>
      <webElementGuid>16778938-cdac-4d7b-8617-23bf8348a8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atomic Habits'])[1]/following::button[1]</value>
      <webElementGuid>d4bf14b4-4975-4fff-85df-93653ed04a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Seven Husbands of Evelyn Hugo'])[1]/preceding::button[1]</value>
      <webElementGuid>35e29a14-1a9b-4f4c-9b90-df518bea01ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>233c071a-11df-4331-be08-5ada6c5cea25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
