<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fantasy_absolute top-4 right-4 bg-gr_b4e9cf</name>
   <tag></tag>
   <elementGuidId>919ebc5e-e5a6-44c7-a4a6-73b9406c8e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[2]/div[4]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.space-y-3 > .relative > .absolute</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcb2e335-0e13-4159-a32c-aafa96a4f8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx:138:14</value>
      <webElementGuid>30593083-4463-45b1-9940-e7ec9a5aba09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52537b4b-3fd7-4e63-95c0-4b8139118ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx</value>
      <webElementGuid>aaa48c67-f24e-4182-a59c-c773875f6b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>138</value>
      <webElementGuid>473fb60a-5e92-4d20-a4d8-8a8ac98cf572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BrowseLibrary.tsx</value>
      <webElementGuid>8128a318-5675-48a3-bc16-aea8d8f62a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0eea733-4872-4586-8200-374ec3e32deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22className%22%3A%22absolute%20top-4%20right-4%20bg-green-500%20text-white%20p-2%20rounded-full%20hover%3Abg-green-600%20transition-colors%20shadow-lg%22%7D</value>
      <webElementGuid>2fece3ea-1b5a-47b3-aef7-540292812534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute top-4 right-4 bg-green-500 text-white p-2 rounded-full hover:bg-green-600 transition-colors shadow-lg</value>
      <webElementGuid>070f1ca4-e176-44ec-8b9c-0c91870cae31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;relative&quot;]/button[@class=&quot;absolute top-4 right-4 bg-green-500 text-white p-2 rounded-full hover:bg-green-600 transition-colors shadow-lg&quot;]</value>
      <webElementGuid>7b6103e0-2d9a-4b6e-a4ed-0fedae81db84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[4]/div/button</value>
      <webElementGuid>81df8cac-533f-402e-8ad8-3af5398a8524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fantasy'])[2]/following::button[1]</value>
      <webElementGuid>aff7a277-c80a-4338-af6d-b297283c13d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Lord of the Rings'])[1]/following::button[1]</value>
      <webElementGuid>7e0e0de2-7366-4705-8a46-a4c5d58424d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>a9ccb12e-8233-4996-88cb-8f8dc2b281f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/preceding::button[2]</value>
      <webElementGuid>12cc750f-fc34-4727-959b-865988176437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>375ae298-946d-45d3-9ac2-9c20d6509253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
