<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BookTracker_p-2 text-gray-600 hovert_d27fbc</name>
   <tag></tag>
   <elementGuidId>ea0a4db4-e3e6-4b58-a14f-52d4d51f2a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/header/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd3dd518-d010-4c80-b368-51eb0b900600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\HeaderNav.tsx:29:10</value>
      <webElementGuid>5ca0d668-1ef9-4811-9042-a4c31359909b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>83cd6c80-84cd-4f70-a473-0a12e78c8c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\HeaderNav.tsx</value>
      <webElementGuid>3cd37282-cf36-4f46-9aeb-f7759eb2c227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>1abe3f96-435c-4e87-b4d1-944cb0d55a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>HeaderNav.tsx</value>
      <webElementGuid>0b94f272-6c9c-42ca-86c8-7cab7ab26e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c08d5d5f-bead-4d05-a115-03d173d31628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22className%22%3A%22p-2%20text-gray-600%20hover%3Atext-gray-800%20transition-colors%20relative%22%7D</value>
      <webElementGuid>2fb32c8b-ffca-49da-a940-6fd9b48e10dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-2 text-gray-600 hover:text-gray-800 transition-colors relative</value>
      <webElementGuid>c7ab2df3-9bf9-48c5-b588-d75ad33b181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/header[@class=&quot;bg-white shadow-sm border-b border-gray-100 px-4 py-4&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;flex items-center space-x-3&quot;]/button[@class=&quot;p-2 text-gray-600 hover:text-gray-800 transition-colors relative&quot;]</value>
      <webElementGuid>b12c8c87-52c3-41af-afc8-61e92f543bf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/header/div/div/button[2]</value>
      <webElementGuid>6c7c58f2-d356-4f52-9836-a7a38b6c674a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BookTracker'])[1]/following::button[2]</value>
      <webElementGuid>fbd7907c-158d-44a4-8458-08092525114b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome back!'])[1]/preceding::button[1]</value>
      <webElementGuid>3e691937-c54a-449b-bfb9-8c679145050b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Reading'])[1]/preceding::button[1]</value>
      <webElementGuid>8430753a-aaec-41b2-9f07-bdd72e2ed371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>beffb28a-ebda-4dae-b997-843318bb5d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
