<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_To Kill a Mockingbird_absolute inset-0 _8efb1a</name>
   <tag></tag>
   <elementGuidId>424d4b31-34d5-416d-b6af-60ccf8fd0d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[3]/div/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^4\.6★1984George Orwell$/ >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80f0862d-4fc5-4c35-8823-136f002e2a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BookCard.tsx:25:10</value>
      <webElementGuid>9c79a102-0068-49c8-81f9-214ca36d94fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb282114-835d-4fa5-a4df-d2f776b03ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BookCard.tsx</value>
      <webElementGuid>9ee1ad5e-f74d-40d1-ba39-a23eced8bbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>915b8771-dce2-4e06-987c-81e33fbcb105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BookCard.tsx</value>
      <webElementGuid>86292488-1623-41eb-bea8-98f164b6412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a60e91fc-9b8a-4a38-951e-bf0f8134a169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22className%22%3A%22absolute%20inset-0%20flex%20items-center%20justify-center%22%7D</value>
      <webElementGuid>cdfef076-49ff-4332-ae25-54477c61d071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 flex items-center justify-center</value>
      <webElementGuid>57487830-23e5-4dad-8209-ce0c03f5ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-6&quot;]/div[3]/div[@class=&quot;grid grid-cols-2 gap-3&quot;]/div[@class=&quot;bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-all duration-200 hover:scale-105&quot;]/div[@class=&quot;aspect-[3/4] bg-gradient-to-br from-blue-100 to-purple-100 relative&quot;]/div[@class=&quot;absolute inset-0 flex items-center justify-center&quot;]</value>
      <webElementGuid>b2b1d63b-8416-497a-a4a2-ebdcf881c7cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[3]/div/div[3]/div/div</value>
      <webElementGuid>a6b0b033-551a-4d45-952b-18fb43b21aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Kill a Mockingbird'])[1]/following::div[3]</value>
      <webElementGuid>dfd4ec3e-11be-4ea9-b780-21bffb118b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Great Gatsby'])[1]/following::div[8]</value>
      <webElementGuid>db7234ef-0f4e-43a9-8fba-2d68b6fd5e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pride and Prejudice'])[1]/preceding::div[6]</value>
      <webElementGuid>f98f23e6-af9a-4218-b07a-af569a7de5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[8]</value>
      <webElementGuid>57aef01a-46d6-4c5d-bf21-c66b01f0677f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div</value>
      <webElementGuid>8eae64cc-3790-45eb-867a-3bc9d48b97cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
