<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The Great Gatsby_absolute inset-0 flex _065962</name>
   <tag></tag>
   <elementGuidId>1eb73ab0-f6cb-40e2-a17f-b199166211d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[3]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^4\.8★To Kill a MockingbirdHarper Lee$/ >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ab78446-8379-4deb-a044-49c36a4531c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BookCard.tsx:25:10</value>
      <webElementGuid>9732a9af-21d6-4cbd-981b-1565cad86346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f80b9bd0-d862-4ede-b23a-466a9e9c2817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BookCard.tsx</value>
      <webElementGuid>c10caa11-bacb-4b53-affb-8860086ca618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>b1c5f683-e9eb-467c-8ee2-d12cbada3ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BookCard.tsx</value>
      <webElementGuid>7b092bd0-829d-46e4-8546-be11896edc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cce1a54e-422c-454f-a8ae-1767bc9c4a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22className%22%3A%22absolute%20inset-0%20flex%20items-center%20justify-center%22%7D</value>
      <webElementGuid>387a1fcc-0ce8-4c1d-89ff-85e6c1dade41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 flex items-center justify-center</value>
      <webElementGuid>e2b24c5f-c93c-4287-adcb-683ad300306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-6&quot;]/div[3]/div[@class=&quot;grid grid-cols-2 gap-3&quot;]/div[@class=&quot;bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-all duration-200 hover:scale-105&quot;]/div[@class=&quot;aspect-[3/4] bg-gradient-to-br from-blue-100 to-purple-100 relative&quot;]/div[@class=&quot;absolute inset-0 flex items-center justify-center&quot;]</value>
      <webElementGuid>5b8452f6-6d84-44fe-b797-3c760759f4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[3]/div/div[2]/div/div</value>
      <webElementGuid>67697aa7-6b8d-4472-a484-cbf9097ee929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Great Gatsby'])[1]/following::div[3]</value>
      <webElementGuid>61cdec5b-1c34-4b1a-adc6-850f8466ec4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended for You'])[1]/following::div[9]</value>
      <webElementGuid>530dad16-569a-4e15-a42e-d4c14b45fce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Kill a Mockingbird'])[1]/preceding::div[2]</value>
      <webElementGuid>5ab68ce7-5773-4c90-bdf3-828bfd5a7e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pride and Prejudice'])[1]/preceding::div[11]</value>
      <webElementGuid>23858259-caf6-4764-9ab3-a9c2a836c7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>e6be50ef-26d7-41b9-b5f4-ea39370be63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
