<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recommended for You_absolute inset-0 fl_7144e8</name>
   <tag></tag>
   <elementGuidId>8631ab42-4da7-48e8-ba78-f71b163d9bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[3]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.absolute.inset-0.flex.items-center.justify-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^4\.2★The Great GatsbyF\. Scott Fitzgerald$/ >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f677477b-39ba-4924-a824-816e817ef9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BookCard.tsx:25:10</value>
      <webElementGuid>fd0a2d92-af99-4527-b66e-967bacbfc10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9fca220-d54f-44fd-941b-4803459b0e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BookCard.tsx</value>
      <webElementGuid>d0dc189e-d176-4c58-9349-c64c8d0909a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>39fd9bff-533a-4afd-bd6c-5a990017a916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BookCard.tsx</value>
      <webElementGuid>40dd526f-9910-48be-a5f5-6a8bb1315242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5eddcd17-81c2-43a6-867c-a87744b1b927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22className%22%3A%22absolute%20inset-0%20flex%20items-center%20justify-center%22%7D</value>
      <webElementGuid>fd943c38-d1a6-40d0-ba3d-13a69bc91c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 flex items-center justify-center</value>
      <webElementGuid>b5ea531c-23b1-4059-a100-82e3ea29c943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-6&quot;]/div[3]/div[@class=&quot;grid grid-cols-2 gap-3&quot;]/div[@class=&quot;bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-all duration-200 hover:scale-105&quot;]/div[@class=&quot;aspect-[3/4] bg-gradient-to-br from-blue-100 to-purple-100 relative&quot;]/div[@class=&quot;absolute inset-0 flex items-center justify-center&quot;]</value>
      <webElementGuid>4c2bc97f-7102-4e2f-85d4-2e8931943e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[3]/div/div/div/div</value>
      <webElementGuid>b93b45be-835a-48cc-8872-50de25902fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended for You'])[1]/following::div[4]</value>
      <webElementGuid>68cc03dc-0078-4149-83f3-ec549dbce67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Great Gatsby'])[1]/preceding::div[2]</value>
      <webElementGuid>824674a0-8fbe-4903-b991-89429dc84ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Kill a Mockingbird'])[1]/preceding::div[6]</value>
      <webElementGuid>05e62800-5b84-477c-af47-987f7b846272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>6e28b7d9-886c-4f6d-8622-f5ff954574be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
