<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BookTracker_root</name>
   <tag></tag>
   <elementGuidId>9e526c73-d9de-49fa-a171-b51af89c3123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bc27506-854e-425f-bfdd-5b1cab18cac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>37021317-8404-4d9e-bb25-60cc524eb391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BookTrackerWelcome back!You've read 245 pages this weekContinue ReadingAtomic HabitsJames ClearPage 120 of 32038%Last read: 2 hours agoThe Seven Husbands of Evelyn HugoTaylor Jenkins ReidPage 45 of 40011%Last read: YesterdayRecommended for You4.2★The Great GatsbyF. Scott Fitzgerald4.8★To Kill a MockingbirdHarper Lee4.6★1984George Orwell4.4★Pride and PrejudiceJane AustenHomeLibraryDiscoverReadingProfile</value>
      <webElementGuid>38fd98b2-f7a2-49a0-bfdf-b1bbafb671bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>959bf11a-a9b4-4e57-b341-67cf01ef1503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>c8efda68-38b4-4e7d-9843-a4ec32c7c20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>5208e19b-0355-4625-9185-b6f7b41d66f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = concat(&quot;BookTrackerWelcome back!You&quot; , &quot;'&quot; , &quot;ve read 245 pages this weekContinue ReadingAtomic HabitsJames ClearPage 120 of 32038%Last read: 2 hours agoThe Seven Husbands of Evelyn HugoTaylor Jenkins ReidPage 45 of 40011%Last read: YesterdayRecommended for You4.2★The Great GatsbyF. Scott Fitzgerald4.8★To Kill a MockingbirdHarper Lee4.6★1984George Orwell4.4★Pride and PrejudiceJane AustenHomeLibraryDiscoverReadingProfile&quot;) or . = concat(&quot;BookTrackerWelcome back!You&quot; , &quot;'&quot; , &quot;ve read 245 pages this weekContinue ReadingAtomic HabitsJames ClearPage 120 of 32038%Last read: 2 hours agoThe Seven Husbands of Evelyn HugoTaylor Jenkins ReidPage 45 of 40011%Last read: YesterdayRecommended for You4.2★The Great GatsbyF. Scott Fitzgerald4.8★To Kill a MockingbirdHarper Lee4.6★1984George Orwell4.4★Pride and PrejudiceJane AustenHomeLibraryDiscoverReadingProfile&quot;))]</value>
      <webElementGuid>6ff88dbe-a97e-4198-b290-b66dc9566483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
