<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse Library_w-full pl-10 pr-4 py-3_c2404c_2</name>
   <tag></tag>
   <elementGuidId>afce55f8-9dec-4bfd-9c32-1d959e934753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='to']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search books or authors...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13686c7d-03da-4092-8389-cf80e6bd031b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx:101:8</value>
      <webElementGuid>91d2119a-0606-4d9d-8904-38f718c04a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87c0b616-cd35-48c4-96a5-f38c4ea1729f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx</value>
      <webElementGuid>c3b29d9c-8316-4a67-9525-57e96a3168ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>7b0fa8a1-d455-4b07-a6f8-fc7e95892920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BrowseLibrary.tsx</value>
      <webElementGuid>7a984be8-dce3-4e03-984e-a644ac4905f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98a23cc1-9765-46b3-b009-8e610f607ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22placeholder%22%3A%22Search%20books%20or%20authors...%22%2C%22className%22%3A%22w-full%20pl-10%20pr-4%20py-3%20bg-gray-100%20rounded-xl%20border-none%20focus%3Aoutline-none%20focus%3Aring-2%20focus%3Aring-blue-500%22%7D</value>
      <webElementGuid>d5acf4a0-b265-42a8-90cc-55310fd1028f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e97a309-5d8d-4be7-82a7-a2a5536dd837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search books or authors...</value>
      <webElementGuid>fdc9d811-d280-4bad-bab7-6940d723e8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>d45388bb-c8d0-444d-b290-c67d81e5e286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>to</value>
      <webElementGuid>32faa32f-6790-4edf-9f20-7d3cc2c32346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500&quot;]</value>
      <webElementGuid>eef5f9a7-5969-49e4-982e-975204ac7646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='to']</value>
      <webElementGuid>26c38356-263f-4ec1-b07d-0045f8e2d29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/input</value>
      <webElementGuid>0c070412-eda8-4f16-bf57-1f16642c285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e4f64e94-d934-4f7d-bf92-08c096411b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search books or authors...']</value>
      <webElementGuid>d6ea53ef-3d8e-4457-b9f7-eafb51c1553e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ro']</value>
      <webElementGuid>061fe145-3536-4a10-94b0-2647a112e91f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
