<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse Library_w-full pl-10 pr-4 py-3_c2404c_1</name>
   <tag></tag>
   <elementGuidId>d7b90f09-54c4-4c84-9491-1a6b9426f35e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='t']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search books or authors...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d012176c-90f2-4d9c-84b7-f19b94df537c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx:101:8</value>
      <webElementGuid>12366759-268c-4ced-ae16-5ec4c3a12389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a7b7efb-1d63-472a-8034-ebf890a55316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx</value>
      <webElementGuid>79d02194-81e0-4be3-8274-d4249c1961f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>d8ad5740-a784-45a5-8278-7be31ddeb599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BrowseLibrary.tsx</value>
      <webElementGuid>a93b50d3-b43b-4c13-9958-ed89f22ef9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5025d37-0677-4255-8bb0-a74e669afc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22placeholder%22%3A%22Search%20books%20or%20authors...%22%2C%22className%22%3A%22w-full%20pl-10%20pr-4%20py-3%20bg-gray-100%20rounded-xl%20border-none%20focus%3Aoutline-none%20focus%3Aring-2%20focus%3Aring-blue-500%22%7D</value>
      <webElementGuid>d1d29342-909b-4374-af6c-bde53638df2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd372b23-d172-40a6-8f86-704f0e8e34f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search books or authors...</value>
      <webElementGuid>45b07a82-69fe-46d4-9b6b-a494219b2896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>9bf676c8-2d45-4c55-bc30-e4280e2910f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>66276aad-4285-41d8-b0b5-e240bbe6041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500&quot;]</value>
      <webElementGuid>fb736099-47f5-458d-ae2b-21e9acce3cb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='t']</value>
      <webElementGuid>82ba3a18-5565-467e-89dc-49dbc69b17e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/input</value>
      <webElementGuid>64db2ea3-dcf9-4b02-9a58-dee7103277f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>74f87364-f7c4-4898-91c7-3ad9ccd122c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search books or authors...']</value>
      <webElementGuid>2deffa8f-35ee-4c29-b600-e1f415a2cbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='r']</value>
      <webElementGuid>5949cf96-8430-4159-af2e-2b923079711f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
