<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse Library_w-full pl-10 pr-4 py-3_c2404c_4</name>
   <tag></tag>
   <elementGuidId>f46dad03-320c-4f3f-8752-f15dfa9ef023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='tolk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search books or authors...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4943fedb-d00d-4e16-a34b-fa150eac3305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx:101:8</value>
      <webElementGuid>bf40b77b-1486-47de-931a-460fa72a8165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ea2e352-341b-484c-b8c8-37846550af44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\BrowseLibrary.tsx</value>
      <webElementGuid>f930fa65-9ad2-4019-a0cf-48a5b79af9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>aeb85458-25ce-4fc7-b5b6-1a14befeeb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>BrowseLibrary.tsx</value>
      <webElementGuid>75c19825-8afa-4e27-94b1-4082f69828cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34216ffb-ed99-405a-a10c-dea1ba5bd2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%22placeholder%22%3A%22Search%20books%20or%20authors...%22%2C%22className%22%3A%22w-full%20pl-10%20pr-4%20py-3%20bg-gray-100%20rounded-xl%20border-none%20focus%3Aoutline-none%20focus%3Aring-2%20focus%3Aring-blue-500%22%7D</value>
      <webElementGuid>62d7ca3b-d41d-42c1-a2f1-ca41719b6ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36f591cc-2ebc-470f-95c9-e05828e55526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search books or authors...</value>
      <webElementGuid>e48f0289-1443-4a97-9ed2-500bf50f987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>9b994687-792f-40c5-8f7a-20d21f557f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tolk</value>
      <webElementGuid>e1757aaf-72ce-46fe-87d0-25d9af06c760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/main[@class=&quot;px-4 py-6 pb-20&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;w-full pl-10 pr-4 py-3 bg-gray-100 rounded-xl border-none focus:outline-none focus:ring-2 focus:ring-blue-500&quot;]</value>
      <webElementGuid>b3032785-44ac-4533-a046-7e08a9c8dfa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='tolk']</value>
      <webElementGuid>1354d4ec-94fa-43c2-9bfe-eb898fdd7895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/input</value>
      <webElementGuid>d32550b9-ada0-4266-bdf1-63e1a10c5bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ebea7c76-7b99-40a4-9892-5f08a7ddb121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search books or authors...']</value>
      <webElementGuid>4e658285-3da4-46fe-92b6-128115d6bf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='rowl']</value>
      <webElementGuid>76723624-6d18-4049-9776-387457ba4b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
