<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_BookTracker_lucide lucide-bell</name>
   <tag></tag>
   <elementGuidId>2efa51c8-1a10-47ed-90e3-bd5046da9528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='BookTracker'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.lucide.lucide-bell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f3dad34a-95fa-4bcc-b7c1-a468b9fee87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>9d5a32e4-cb23-4b14-acbd-22165896f4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>82aeaa7f-34ce-4c89-8ab9-788f8f07adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e77f10d2-5e9d-49bd-b557-83ef20891f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>6d83eaa6-9e2a-4469-8bf5-f6c2d60f8793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a3a1820a-1678-49cc-bb99-79878bfe48c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>b12e3cac-c0a1-4f7a-8821-459cc3f78df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>008ed252-4894-413c-8e37-1967319d5e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>3354b422-4d55-4c09-96ba-6c21d79544c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>1c301cf9-d3a0-4fca-ac98-c7ef6ed0b915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-bell</value>
      <webElementGuid>0bcbb7ef-160c-4be2-a640-400af89f364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-id</name>
      <type>Main</type>
      <value>src\components\HeaderNav.tsx:30:12</value>
      <webElementGuid>05c85d7b-8c21-4bea-9577-9faf1b6c8f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lov-name</name>
      <type>Main</type>
      <value>Bell</value>
      <webElementGuid>6148549d-8a55-421e-aceb-2ad4a3bc6029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-path</name>
      <type>Main</type>
      <value>src\components\HeaderNav.tsx</value>
      <webElementGuid>51055cf4-8165-4b6f-8260-a280f8379030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-line</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>5f401c31-4e7d-407b-a167-e8c14bb37777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-file</name>
      <type>Main</type>
      <value>HeaderNav.tsx</value>
      <webElementGuid>c3518e74-aaec-4ce7-9fe7-1ef0806aeb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>Bell</value>
      <webElementGuid>d6590ff4-ca2c-4ced-95b4-7125219ab4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-content</name>
      <type>Main</type>
      <value>%7B%7D</value>
      <webElementGuid>bc8fb535-3304-4e29-99bc-d9364ea6f01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-gray-50 max-w-md mx-auto&quot;]/header[@class=&quot;bg-white shadow-sm border-b border-gray-100 px-4 py-4&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;flex items-center space-x-3&quot;]/button[@class=&quot;p-2 text-gray-600 hover:text-gray-800 transition-colors relative&quot;]/svg[@class=&quot;lucide lucide-bell&quot;]</value>
      <webElementGuid>515e4291-220e-424a-ab7c-822229c442c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BookTracker'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>fc3e21e0-9733-46a0-867e-2b78d94d97dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome back!'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>d71b7e02-d792-4573-ac4f-73d3fe65fdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Reading'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>676e1d73-ffb4-4162-b9ae-a5c37bc4f145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
